# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'history.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *


class History(QMainWindow):
    def __init__(self):
        super(History, self).__init__()
        self.setupUi(self)

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1920, 1080)
        self.history_1 = QLabel(Form)
        self.history_1.setGeometry(QtCore.QRect(30, 30, 734, 473))
        self.history_1.setObjectName("history_1")
        self.history_1.setPixmap(QPixmap("../../images/school_map.jpg"))
        self.history_1.setScaledContents(True)

        self.history_2 = QLabel(Form)
        self.history_2.setGeometry(QtCore.QRect(960, 30, 734, 473))
        self.history_2.setObjectName("history_2")
        self.history_2.setPixmap(QPixmap("../../images/school_map_change.jpg"))
        self.history_2.setScaledContents(True)

        self.retranslateUi(Form)
        QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))


if __name__ == '__main__':
    app = QApplication(sys.argv)
    desktop = QApplication.desktop()
    s = "test"
    print(s)
    t = History()
    t.show()
    sys.exit(app.exec_())
