# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widget.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(1920, 1080)
        Widget.setMinimumSize(QtCore.QSize(1920, 1080))
        Widget.setMaximumSize(QtCore.QSize(1920, 1080))
        Widget.setStyleSheet("")
        self.schoolmap = QtWidgets.QLabel(Widget)
        self.schoolmap.setGeometry(QtCore.QRect(0, 135, 1468, 945))
        self.schoolmap.setStyleSheet("border-image: url(:/images/imgs/school_map.jpg);")
        self.schoolmap.setText("")
        self.schoolmap.setPixmap(QtGui.QPixmap(":/img/images/school_map.jpg"))
        self.schoolmap.setObjectName("schoolmap")
        self.biaoti = QtWidgets.QLabel(Widget)
        self.biaoti.setGeometry(QtCore.QRect(160, 0, 1301, 135))
        font = QtGui.QFont()
        font.setFamily("陈静的字完整版")
        font.setPointSize(48)
        self.biaoti.setFont(font)
        self.biaoti.setObjectName("biaoti")
        self.MainText = QtWidgets.QTextBrowser(Widget)
        self.MainText.setGeometry(QtCore.QRect(1480, 260, 400, 800))
        self.MainText.setMinimumSize(QtCore.QSize(400, 800))
        self.MainText.setMaximumSize(QtCore.QSize(400, 800))
        self.MainText.setObjectName("MainText")
        self.xiaohui = QtWidgets.QLabel(Widget)
        self.xiaohui.setGeometry(QtCore.QRect(200, 10, 111, 111))
        self.xiaohui.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.xiaohui.setText("")
        self.xiaohui.setPixmap(QtGui.QPixmap(":/img/images/xiaohui_2.png"))
        self.xiaohui.setScaledContents(True)
        self.xiaohui.setObjectName("xiaohui")
        self.tubiao_1 = QtWidgets.QLabel(Widget)
        self.tubiao_1.setGeometry(QtCore.QRect(1290, 10, 121, 111))
        self.tubiao_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tubiao_1.setAutoFillBackground(False)
        self.tubiao_1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tubiao_1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tubiao_1.setText("")
        self.tubiao_1.setTextFormat(QtCore.Qt.AutoText)
        self.tubiao_1.setPixmap(QtGui.QPixmap(":/img/images/t1.png"))
        self.tubiao_1.setScaledContents(True)
        self.tubiao_1.setObjectName("tubiao_1")
        self.layoutWidget = QtWidgets.QWidget(Widget)
        self.layoutWidget.setGeometry(QtCore.QRect(1480, 10, 405, 241))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Timer = QtWidgets.QLabel(self.layoutWidget)
        self.Timer.setObjectName("Timer")
        self.verticalLayout.addWidget(self.Timer)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.test_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.test_2.setEnabled(True)
        self.test_2.setMinimumSize(QtCore.QSize(95, 50))
        self.test_2.setMaximumSize(QtCore.QSize(95, 50))
        self.test_2.setObjectName("test_2")
        self.horizontalLayout.addWidget(self.test_2)
        self.test_3 = QtWidgets.QPushButton(self.layoutWidget)
        self.test_3.setMinimumSize(QtCore.QSize(95, 50))
        self.test_3.setMaximumSize(QtCore.QSize(95, 50))
        self.test_3.setObjectName("test_3")
        self.horizontalLayout.addWidget(self.test_3)
        self.test = QtWidgets.QPushButton(self.layoutWidget)
        self.test.setMinimumSize(QtCore.QSize(95, 50))
        self.test.setMaximumSize(QtCore.QSize(95, 50))
        self.test.setObjectName("test")
        self.horizontalLayout.addWidget(self.test)
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton.setMinimumSize(QtCore.QSize(95, 50))
        self.pushButton.setMaximumSize(QtCore.QSize(95, 50))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.view_model = QtWidgets.QPushButton(self.layoutWidget)
        self.view_model.setMinimumSize(QtCore.QSize(95, 50))
        self.view_model.setMaximumSize(QtCore.QSize(95, 50))
        self.view_model.setObjectName("view_model")
        self.horizontalLayout_3.addWidget(self.view_model)
        self.guide_model = QtWidgets.QPushButton(self.layoutWidget)
        self.guide_model.setMinimumSize(QtCore.QSize(95, 50))
        self.guide_model.setMaximumSize(QtCore.QSize(95, 50))
        self.guide_model.setObjectName("guide_model")
        self.horizontalLayout_3.addWidget(self.guide_model)
        self.school_intro = QtWidgets.QPushButton(self.layoutWidget)
        self.school_intro.setMinimumSize(QtCore.QSize(95, 50))
        self.school_intro.setMaximumSize(QtCore.QSize(95, 50))
        self.school_intro.setObjectName("school_intro")
        self.horizontalLayout_3.addWidget(self.school_intro)
        self.how_to_use = QtWidgets.QPushButton(self.layoutWidget)
        self.how_to_use.setMinimumSize(QtCore.QSize(95, 50))
        self.how_to_use.setMaximumSize(QtCore.QSize(95, 50))
        self.how_to_use.setObjectName("how_to_use")
        self.horizontalLayout_3.addWidget(self.how_to_use)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.groupBox = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox.setEnabled(True)
        self.groupBox.setMouseTracking(False)
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(30, 30, 361, 21))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.TSP_button = QtWidgets.QRadioButton(self.layoutWidget1)
        self.TSP_button.setObjectName("TSP_button")
        self.horizontalLayout_2.addWidget(self.TSP_button)
        self.TSPwr_button = QtWidgets.QRadioButton(self.layoutWidget1)
        self.TSPwr_button.setObjectName("TSPwr_button")
        self.horizontalLayout_2.addWidget(self.TSPwr_button)
        self.by_order_button = QtWidgets.QRadioButton(self.layoutWidget1)
        self.by_order_button.setObjectName("by_order_button")
        self.horizontalLayout_2.addWidget(self.by_order_button)
        self.verticalLayout.addWidget(self.groupBox)
        self.A1 = QtWidgets.QPushButton(Widget)
        self.A1.setGeometry(QtCore.QRect(550, 280, 101, 21))
        self.A1.setObjectName("A1")
        self.A2 = QtWidgets.QPushButton(Widget)
        self.A2.setGeometry(QtCore.QRect(680, 240, 71, 71))
        self.A2.setObjectName("A2")
        self.A0 = QtWidgets.QPushButton(Widget)
        self.A0.setGeometry(QtCore.QRect(550, 250, 101, 21))
        self.A0.setObjectName("A0")
        self.A3 = QtWidgets.QPushButton(Widget)
        self.A3.setGeometry(QtCore.QRect(750, 240, 93, 31))
        self.A3.setObjectName("A3")
        self.A4 = QtWidgets.QPushButton(Widget)
        self.A4.setGeometry(QtCore.QRect(750, 280, 93, 31))
        self.A4.setObjectName("A4")
        self.A5 = QtWidgets.QPushButton(Widget)
        self.A5.setGeometry(QtCore.QRect(840, 250, 61, 28))
        self.A5.setObjectName("A5")
        self.A6 = QtWidgets.QPushButton(Widget)
        self.A6.setGeometry(QtCore.QRect(840, 280, 61, 41))
        self.A6.setObjectName("A6")
        self.A7 = QtWidgets.QPushButton(Widget)
        self.A7.setGeometry(QtCore.QRect(900, 290, 71, 28))
        self.A7.setObjectName("A7")
        self.A9 = QtWidgets.QPushButton(Widget)
        self.A9.setGeometry(QtCore.QRect(540, 330, 111, 51))
        self.A9.setObjectName("A9")
        self.A8 = QtWidgets.QPushButton(Widget)
        self.A8.setGeometry(QtCore.QRect(450, 390, 51, 61))
        self.A8.setObjectName("A8")
        self.A10 = QtWidgets.QPushButton(Widget)
        self.A10.setGeometry(QtCore.QRect(540, 380, 41, 91))
        self.A10.setObjectName("A10")
        self.A11 = QtWidgets.QPushButton(Widget)
        self.A11.setGeometry(QtCore.QRect(540, 460, 121, 61))
        self.A11.setObjectName("A11")
        self.A12 = QtWidgets.QPushButton(Widget)
        self.A12.setGeometry(QtCore.QRect(700, 357, 111, 31))
        self.A12.setObjectName("A12")
        self.A13 = QtWidgets.QPushButton(Widget)
        self.A13.setGeometry(QtCore.QRect(750, 390, 81, 51))
        self.A13.setObjectName("A13")
        self.A14 = QtWidgets.QPushButton(Widget)
        self.A14.setGeometry(QtCore.QRect(680, 460, 121, 61))
        self.A14.setObjectName("A14")
        self.A15 = QtWidgets.QPushButton(Widget)
        self.A15.setGeometry(QtCore.QRect(810, 450, 61, 41))
        self.A15.setObjectName("A15")
        self.A16 = QtWidgets.QPushButton(Widget)
        self.A16.setGeometry(QtCore.QRect(840, 330, 151, 28))
        self.A16.setObjectName("A16")
        self.A17 = QtWidgets.QPushButton(Widget)
        self.A17.setGeometry(QtCore.QRect(890, 360, 93, 151))
        self.A17.setObjectName("A17")
        self.A18 = QtWidgets.QPushButton(Widget)
        self.A18.setGeometry(QtCore.QRect(1010, 400, 93, 61))
        self.A18.setObjectName("A18")
        self.A19 = QtWidgets.QPushButton(Widget)
        self.A19.setGeometry(QtCore.QRect(1010, 330, 61, 51))
        self.A19.setObjectName("A19")
        self.A20 = QtWidgets.QPushButton(Widget)
        self.A20.setGeometry(QtCore.QRect(1010, 480, 101, 41))
        self.A20.setObjectName("A20")
        self.A21 = QtWidgets.QPushButton(Widget)
        self.A21.setGeometry(QtCore.QRect(540, 620, 71, 81))
        self.A21.setObjectName("A21")
        self.A22 = QtWidgets.QPushButton(Widget)
        self.A22.setGeometry(QtCore.QRect(630, 610, 71, 81))
        self.A22.setObjectName("A22")
        self.A32 = QtWidgets.QPushButton(Widget)
        self.A32.setGeometry(QtCore.QRect(730, 570, 151, 51))
        self.A32.setObjectName("A32")
        self.A24 = QtWidgets.QPushButton(Widget)
        self.A24.setGeometry(QtCore.QRect(730, 620, 71, 51))
        self.A24.setAcceptDrops(False)
        self.A24.setObjectName("A24")
        self.A25 = QtWidgets.QPushButton(Widget)
        self.A25.setGeometry(QtCore.QRect(730, 670, 71, 41))
        self.A25.setObjectName("A25")
        self.A26 = QtWidgets.QPushButton(Widget)
        self.A26.setGeometry(QtCore.QRect(730, 710, 71, 41))
        self.A26.setObjectName("A26")
        self.A27 = QtWidgets.QPushButton(Widget)
        self.A27.setGeometry(QtCore.QRect(800, 620, 81, 28))
        self.A27.setObjectName("A27")
        self.A28 = QtWidgets.QPushButton(Widget)
        self.A28.setGeometry(QtCore.QRect(800, 650, 81, 28))
        self.A28.setObjectName("A28")
        self.A29 = QtWidgets.QPushButton(Widget)
        self.A29.setGeometry(QtCore.QRect(800, 690, 93, 28))
        self.A29.setObjectName("A29")
        self.A30 = QtWidgets.QPushButton(Widget)
        self.A30.setGeometry(QtCore.QRect(810, 720, 71, 28))
        self.A30.setObjectName("A30")
        self.A31 = QtWidgets.QPushButton(Widget)
        self.A31.setGeometry(QtCore.QRect(910, 580, 131, 151))
        self.A31.setObjectName("A31")
        self.A32_2 = QtWidgets.QPushButton(Widget)
        self.A32_2.setGeometry(QtCore.QRect(1050, 550, 111, 61))
        self.A32_2.setObjectName("A32_2")
        self.A33 = QtWidgets.QPushButton(Widget)
        self.A33.setGeometry(QtCore.QRect(1190, 547, 81, 141))
        self.A33.setObjectName("A33")
        self.A34 = QtWidgets.QPushButton(Widget)
        self.A34.setGeometry(QtCore.QRect(1072, 620, 101, 61))
        self.A34.setObjectName("A34")
        self.A35 = QtWidgets.QPushButton(Widget)
        self.A35.setGeometry(QtCore.QRect(490, 770, 93, 61))
        self.A35.setObjectName("A35")
        self.A36 = QtWidgets.QPushButton(Widget)
        self.A36.setGeometry(QtCore.QRect(620, 780, 93, 101))
        self.A36.setObjectName("A36")
        self.A37 = QtWidgets.QPushButton(Widget)
        self.A37.setGeometry(QtCore.QRect(760, 780, 91, 28))
        self.A37.setObjectName("A37")
        self.A38 = QtWidgets.QPushButton(Widget)
        self.A38.setGeometry(QtCore.QRect(760, 810, 93, 28))
        self.A38.setObjectName("A38")
        self.A39 = QtWidgets.QPushButton(Widget)
        self.A39.setGeometry(QtCore.QRect(770, 890, 111, 71))
        self.A39.setObjectName("A39")
        self.A40 = QtWidgets.QPushButton(Widget)
        self.A40.setGeometry(QtCore.QRect(620, 960, 93, 61))
        self.A40.setObjectName("A40")
        self.A41 = QtWidgets.QPushButton(Widget)
        self.A41.setGeometry(QtCore.QRect(930, 810, 221, 131))
        self.A41.setObjectName("A41")
        self.A42 = QtWidgets.QPushButton(Widget)
        self.A42.setGeometry(QtCore.QRect(1140, 720, 81, 61))
        self.A42.setObjectName("A42")
        self.A43 = QtWidgets.QPushButton(Widget)
        self.A43.setGeometry(QtCore.QRect(1172, 830, 101, 31))
        self.A43.setObjectName("A43")
        self.A44 = QtWidgets.QPushButton(Widget)
        self.A44.setGeometry(QtCore.QRect(1220, 800, 93, 31))
        self.A44.setObjectName("A44")
        self.A45 = QtWidgets.QPushButton(Widget)
        self.A45.setGeometry(QtCore.QRect(1250, 750, 81, 28))
        self.A45.setObjectName("A45")
        self.A46 = QtWidgets.QPushButton(Widget)
        self.A46.setGeometry(QtCore.QRect(790, 180, 93, 61))
        self.A46.setObjectName("A46")

        self.A0.s

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "校园导航系统 by clb"))
        self.biaoti.setText(_translate("Widget", "<html><head/><body><p align=\"center\">北京工业大学校园导航系统</p></body></html>"))
        self.Timer.setText(_translate("Widget", "<html><head/><body><p align=\"center\">放时间</p></body></html>"))
        self.test_2.setText(_translate("Widget", "浏览模式"))
        self.test_3.setText(_translate("Widget", "导航模式"))
        self.test.setText(_translate("Widget", "校园简介"))
        self.pushButton.setText(_translate("Widget", "使用说明"))
        self.view_model.setText(_translate("Widget", "浏览模式"))
        self.guide_model.setText(_translate("Widget", "导航模式"))
        self.school_intro.setText(_translate("Widget", "校园简介"))
        self.how_to_use.setText(_translate("Widget", "使用说明"))
        self.groupBox.setTitle(_translate("Widget", "模式选择"))
        self.TSP_button.setText(_translate("Widget", "TSP"))
        self.TSPwr_button.setText(_translate("Widget", "TSP without return"))
        self.by_order_button.setText(_translate("Widget", "by order"))
        self.A1.setToolTip(_translate("Widget", "宿舍2号楼"))
        self.A1.setText(_translate("Widget", "1"))
        self.A2.setToolTip(_translate("Widget", "天天餐厅&学生综合服务大厅"))
        self.A2.setText(_translate("Widget", "2"))
        self.A0.setToolTip(_translate("Widget", "宿舍1号楼"))
        self.A0.setText(_translate("Widget", "0"))
        self.A3.setToolTip(_translate("Widget", "宿舍3号楼"))
        self.A3.setText(_translate("Widget", "3"))
        self.A4.setToolTip(_translate("Widget", "宿舍4号楼"))
        self.A4.setText(_translate("Widget", "4"))
        self.A5.setToolTip(_translate("Widget", "校医院"))
        self.A5.setText(_translate("Widget", "5"))
        self.A6.setToolTip(_translate("Widget", "北浴室"))
        self.A6.setText(_translate("Widget", "6"))
        self.A7.setToolTip(_translate("Widget", "金工楼"))
        self.A7.setText(_translate("Widget", "7"))
        self.A9.setToolTip(_translate("Widget", "第一教学楼"))
        self.A9.setText(_translate("Widget", "9"))
        self.A8.setToolTip(_translate("Widget", "西门"))
        self.A8.setText(_translate("Widget", "8"))
        self.A10.setToolTip(_translate("Widget", "第二教学楼"))
        self.A10.setText(_translate("Widget", "10"))
        self.A11.setToolTip(_translate("Widget", "材料楼"))
        self.A11.setText(_translate("Widget", "11"))
        self.A12.setToolTip(_translate("Widget", "旧图书馆"))
        self.A12.setText(_translate("Widget", "12"))
        self.A13.setToolTip(_translate("Widget", "礼堂"))
        self.A13.setText(_translate("Widget", "13"))
        self.A14.setToolTip(_translate("Widget", "数理楼"))
        self.A14.setText(_translate("Widget", "14"))
        self.A15.setToolTip(_translate("Widget", "游泳馆"))
        self.A15.setText(_translate("Widget", "15"))
        self.A16.setToolTip(_translate("Widget", "宿舍10&11号楼"))
        self.A16.setText(_translate("Widget", "16"))
        self.A17.setToolTip(_translate("Widget", "北操"))
        self.A17.setText(_translate("Widget", "17"))
        self.A18.setToolTip(_translate("Widget", "宿舍13&14号楼"))
        self.A18.setText(_translate("Widget", "18"))
        self.A19.setToolTip(_translate("Widget", "东门"))
        self.A19.setText(_translate("Widget", "19"))
        self.A20.setToolTip(_translate("Widget", "能源楼"))
        self.A20.setText(_translate("Widget", "20"))
        self.A21.setToolTip(_translate("Widget", "A21"))
        self.A21.setStatusTip(_translate("Widget", "信息楼"))
        self.A21.setText(_translate("Widget", "21"))
        self.A22.setStatusTip(_translate("Widget", "逸夫图书馆"))
        self.A22.setText(_translate("Widget", "22"))
        self.A32.setStatusTip(_translate("Widget", "第三教学楼"))
        self.A32.setText(_translate("Widget", "23"))
        self.A24.setToolTip(_translate("Widget", "知心园"))
        self.A24.setText(_translate("Widget", "24"))
        self.A25.setToolTip(_translate("Widget", "宿舍9号楼"))
        self.A25.setText(_translate("Widget", "25"))
        self.A26.setToolTip(_translate("Widget", "美食园"))
        self.A26.setText(_translate("Widget", "26"))
        self.A27.setToolTip(_translate("Widget", "宿舍7号楼"))
        self.A27.setText(_translate("Widget", "27"))
        self.A28.setToolTip(_translate("Widget", "宿舍8号楼"))
        self.A28.setText(_translate("Widget", "28"))
        self.A29.setToolTip(_translate("Widget", "宿舍12号楼"))
        self.A29.setText(_translate("Widget", "29"))
        self.A30.setToolTip(_translate("Widget", "奥运餐厅"))
        self.A30.setText(_translate("Widget", "30"))
        self.A31.setToolTip(_translate("Widget", "南操"))
        self.A31.setText(_translate("Widget", "31"))
        self.A32_2.setToolTip(_translate("Widget", "第四教学楼"))
        self.A32_2.setText(_translate("Widget", "32"))
        self.A33.setToolTip(_translate("Widget", "理科楼"))
        self.A33.setText(_translate("Widget", "33"))
        self.A34.setToolTip(_translate("Widget", "艺术楼"))
        self.A34.setText(_translate("Widget", "34"))
        self.A35.setToolTip(_translate("Widget", "经管楼"))
        self.A35.setText(_translate("Widget", "35"))
        self.A36.setToolTip(_translate("Widget", "科学楼"))
        self.A36.setText(_translate("Widget", "36"))
        self.A37.setToolTip(_translate("Widget", "宿舍5号楼"))
        self.A37.setText(_translate("Widget", "37"))
        self.A38.setToolTip(_translate("Widget", "宿舍6号楼"))
        self.A38.setText(_translate("Widget", "38"))
        self.A39.setToolTip(_translate("Widget", "人文楼"))
        self.A39.setText(_translate("Widget", "39"))
        self.A40.setToolTip(_translate("Widget", "南门"))
        self.A40.setText(_translate("Widget", "40"))
        self.A41.setToolTip(_translate("Widget", "奥运场馆"))
        self.A41.setText(_translate("Widget", "41"))
        self.A42.setToolTip(_translate("Widget", "月亮湖"))
        self.A42.setText(_translate("Widget", "42"))
        self.A43.setToolTip(_translate("Widget", "知行楼(实训楼)"))
        self.A43.setText(_translate("Widget", "43"))
        self.A44.setText(_translate("Widget", "44"))
        self.A45.setToolTip(_translate("Widget", "软件楼"))
        self.A45.setText(_translate("Widget", "45"))
        self.A46.setToolTip(_translate("Widget", "北门"))
        self.A46.setText(_translate("Widget", "46"))
import test_rc
